apiVersion: v1
kind: Secret
metadata:
  name: sbf-worker-propertyinfo-secret
  namespace: camunda-workers
data:
  FB_USER: <username>           # echo -n <username> | base64
  FB_PASSWD: <password>         # # echo -n <password> | base64
